# Generated by Django 6.0.3 on 2026-04-04 06:03

import uuid
from typing import TYPE_CHECKING, ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.migration import SwappableTuple


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar[list[SwappableTuple]] = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[migrations.CreateModel]] = [
        migrations.CreateModel(
            name="AccountToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("home_country", models.CharField(max_length=2)),
                ("client_country", models.CharField(max_length=2)),
                ("max_working_days", models.PositiveIntegerField()),
                ("working_hours_per_day", models.PositiveIntegerField(default=8)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="guest", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("country_code", models.CharField(max_length=2)),
                ("year", models.PositiveIntegerField()),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("country_code", "year", "date"), name="unique_country_year_date")
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeOff",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("hours", models.PositiveIntegerField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_off", to="wad.contract"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("contract", "date"), name="unique_contract_date")],
            },
        ),
    ]
