# Generated by Django 6.0.3 on 2026-05-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0002_calendartoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="external_calendar_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
