# Generated by Django 6.0.3 on 2026-08-15 07:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import wad.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0003_contract_external_calendar_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="send_to_ksef",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
                ("address", models.CharField(max_length=512)),
                ("country", models.CharField(max_length=2)),
                ("tax_id", models.CharField(blank=True, default="", max_length=50)),
                ("tax_ids", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="buyers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="wad.buyer",
            ),
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=512)),
                ("address", models.CharField(max_length=512)),
                ("country", models.CharField(default="PL", max_length=2)),
                ("nip", models.CharField(blank=True, default="", max_length=10)),
                ("tax_ids", models.TextField(blank=True, default="")),
                ("ksef_token", wad.fields.EncryptedTextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sellers", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=200)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("seller_name", models.CharField(max_length=512)),
                ("seller_address", models.CharField(max_length=512)),
                ("seller_nip", models.CharField(blank=True, default="", max_length=10)),
                ("seller_country", models.CharField(blank=True, default="", max_length=2)),
                ("buyer_name", models.CharField(max_length=512)),
                ("buyer_address", models.CharField(max_length=512)),
                ("buyer_country", models.CharField(max_length=2)),
                ("buyer_tax_id", models.CharField(blank=True, default="", max_length=50)),
                ("seller_tax_ids", models.TextField(blank=True, default="")),
                ("buyer_tax_ids", models.TextField(blank=True, default="")),
                ("vat_note", models.TextField(blank=True, default="")),
                ("account_holder", models.CharField(blank=True, default="", max_length=512)),
                ("iban", models.CharField(blank=True, default="", max_length=64)),
                ("bic", models.CharField(blank=True, default="", max_length=16)),
                ("payment_reference", models.CharField(blank=True, default="", max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("issued", "Issued"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("xml", models.BinaryField(blank=True, null=True)),
                ("xml_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("session_reference", models.CharField(blank=True, default="", max_length=200)),
                ("invoice_reference", models.CharField(blank=True, default="", max_length=200)),
                ("session_state", models.TextField(blank=True, default="")),
                ("ksef_number", models.CharField(blank=True, default="", max_length=50)),
                ("upo", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="wad.buyer",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="wad.contract"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="wad.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="wad.seller",
            ),
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField()),
                ("description", models.CharField(max_length=512)),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=12)),
                ("unit", models.CharField(default="day", max_length=50)),
                ("unit_net_price", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="wad.invoice"
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(fields=("invoice", "position"), name="unique_invoice_line_position")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(fields=("user", "number"), name="unique_invoice_number_per_user"),
        ),
    ]
