# Generated by Django 6.1 on 2026-08-24 17:30

from __future__ import annotations

import uuid
from decimal import ROUND_HALF_UP, Decimal
from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps

GROSZ = Decimal("0.01")

# Art. 81 ust. 2e, in the order revenue reaches them.
SHARES = (Decimal("0.6"), Decimal("1.0"), Decimal("1.8"))

# The wage each year's bases are worked out from: przecietne miesieczne wynagrodzenie w
# sektorze przedsiebiorstw wlacznie z wyplatami z zysku, in the fourth quarter of the year
# before, announced by the Prezes GUS in Monitor Polski each January.
#
# GUS issues a second obwieszczenie the same day, bez wyplat nagrod z zysku, which for 2026 is
# 9 228.30 against 9 228.64. They are made under different statutes, and the one the health
# contribution is defined by is art. 5 pkt 31 ustawy o swiadczeniach opieki zdrowotnej. 2026 is
# M.P. 2026 poz. 117 and 2025 is the same obwieszczenie a year earlier. Taken from those rather
# than from commentary, which carries figures from a reform proposal that never took effect.
PUBLISHED = [
    (2025, Decimal("8549.18")),
    (2026, Decimal("9228.64")),
]


def _bases(wage: Decimal) -> tuple[Decimal, ...]:
    """The three monthly bases a year's health contribution is worked out from.

    Worked out from the one announced figure rather than listed, so the three cannot disagree
    with each other or with the wage they come from. What checks a year is right is ZUS's own
    published contribution: 9 percent of these is 498.35, 830.58 and 1495.04 for 2026.
    """
    return tuple((wage * share).quantize(GROSZ, rounding=ROUND_HALF_UP) for share in SHARES)


def load(apps: StateApps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Enter the years already published, so an instance starts able to place a contribution."""
    model = apps.get_model("wad", "HealthContributionYear")

    rows = []
    for year, wage in PUBLISHED:
        lower, middle, upper = _bases(wage)
        rows.append(model(year=year, lower_base=lower, middle_base=middle, upper_base=upper))

    model.objects.bulk_create(rows)


def unload(apps: StateApps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    model = apps.get_model("wad", "HealthContributionYear")
    model.objects.filter(year__in=[year for year, *_ in PUBLISHED]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0004_invoicing"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthContributionYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(unique=True)),
                ("lower_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("middle_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("upper_base", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="buyer",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="contract",
            name="ryczalt_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_cause",
            field=models.CharField(
                blank=True,
                choices=[("mistake", "A mistake on the invoice"), ("later_event", "Something that happened after it")],
                default="",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="correction_reason",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AddField(
            model_name="invoice",
            name="corrects",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="corrections",
                to="wad.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="paid_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_pln",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_rate",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_rate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_rate_table",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="invoice",
            name="revenue_pln",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="revenue_rate",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="revenue_rate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="revenue_rate_table",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="invoice",
            name="ryczalt_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="business_started_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="seller",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="seller",
            name="kod_urzedu",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AddField(
            model_name="seller",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=81),
        ),
        migrations.CreateModel(
            name="ContributionPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("paid_on", models.DateField()),
                ("social", models.DecimalField(decimal_places=2, default=Decimal(0), max_digits=12)),
                ("health", models.DecimalField(decimal_places=2, default=Decimal(0), max_digits=12)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_payments",
                        to="wad.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CurrencySale",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sold_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("reference", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_sales",
                        to="wad.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recipient", models.EmailField(max_length=254)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                ("message_id", models.CharField(blank=True, default="", max_length=200)),
                ("pdf_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="wad.invoice"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "deliveries",
                "ordering": ["-attempted_at"],
            },
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("xml", models.BinaryField()),
                ("xml_sha256", models.CharField(max_length=64)),
                ("produced_at", models.DateTimeField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=14)),
                ("entry_count", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("produced", "Produced"),
                            ("sending", "Sending"),
                            ("filed", "Filed"),
                            ("rejected", "Rejected"),
                        ],
                        default="produced",
                        max_length=10,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, default="", max_length=64)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("upo", models.TextField(blank=True, default="")),
                ("filed_on", models.DateField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="filings", to="wad.seller"
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-produced_at"],
            },
        ),
        migrations.CreateModel(
            name="TaxPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("covers", models.DateField()),
                ("paid_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tax_payments", to="wad.seller"
                    ),
                ),
            ],
            options={
                "ordering": ["-covers", "-paid_on"],
            },
        ),
        migrations.CreateModel(
            name="TaxReturn",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("filed_on", models.DateField()),
                ("upo", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tax_returns", to="wad.seller"
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "constraints": [models.UniqueConstraint(fields=("seller", "year"), name="unique_return_per_year")],
            },
        ),
        migrations.RunPython(load, unload),
    ]
