# Generated by Django 6.1 on 2026-09-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0006_contract_invoice_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="zus_account",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
