# Generated by Django 6.1 on 2026-09-10 10:58

from __future__ import annotations

import uuid
from decimal import Decimal
from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor
    from django.db.migrations.state import StateApps

# The two wages a year's bases are worked out from: the minimum wage set by rozporzadzenie
# Rady Ministrow, 4 806.00 for 2026, and the prognozowane przecietne wynagrodzenie miesieczne
# w gospodarce narodowej from the budget act, 9 420.00. They give a preferential base of
# 1 441.80 and a full base of 5 652.00, which is what ZUS published its 2026 contributions
# from.
#
# Only 2026. The 2027 minimum wage was proposed at 4 950.00 in June 2026 and is fixed by
# regulation by 15 September 2026; a proposal is not an announcement, so it is not here.
PUBLISHED = [
    (2026, Decimal("4806.00"), None, Decimal("9420.00")),
]


def load(apps: StateApps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Enter the years already announced, so an instance starts able to work a month out."""
    model = apps.get_model("wad", "SocialContributionYear")

    model.objects.bulk_create(
        [
            model(
                year=year,
                minimum_wage=minimum_wage,
                minimum_wage_from_july=from_july,
                forecast_average_wage=forecast_wage,
            )
            for year, minimum_wage, from_july, forecast_wage in PUBLISHED
        ]
    )


def unload(apps: StateApps, _schema_editor: BaseDatabaseSchemaEditor) -> None:
    model = apps.get_model("wad", "SocialContributionYear")
    model.objects.filter(year__in=[year for year, *_ in PUBLISHED]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0007_seller_zus_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialContributionYear",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(unique=True)),
                ("minimum_wage", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "minimum_wage_from_july",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("forecast_average_wage", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="seller",
            name="ulga_na_start",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seller",
            name="preferential_contributions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seller",
            name="chorobowe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="seller",
            name="accident_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("1.67"), max_digits=5),
        ),
        migrations.AddField(
            model_name="contributionpayment",
            name="covers",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contributionpayment",
            name="settles_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContributionHoliday",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("month", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_holidays",
                        to="wad.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "constraints": [models.UniqueConstraint(fields=("seller", "month"), name="unique_holiday_per_month")],
            },
        ),
        # Nothing writes a note against a contribution payment: what a payment settles is the
        # month or the year it names, and both are fields of their own above.
        migrations.RemoveField(
            model_name="contributionpayment",
            name="note",
        ),
        migrations.RunPython(load, unload),
    ]
