# Generated by Django 6.1 on 2026-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0008_social_contributions"),
    ]

    # What a subscription carries and when it announces it. The defaults leave every URL already
    # out there as it was: both kinds carried, which is what the one feed held before there was
    # anything to choose, and no alarms, an alarm being something a reader asks for rather than
    # something a deploy starts doing to them.
    operations = [
        migrations.AddField(
            model_name="calendartoken",
            name="includes_deadlines",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="calendartoken",
            name="includes_time_off",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="calendartoken",
            name="annual_reminder_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="calendartoken",
            name="monthly_reminder_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="calendartoken",
            name="time_off_reminder_days",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
