# Generated by Django 6.1 on 2026-09-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0009_calendar_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="contract",
            name="day_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
