# Generated by Django 6.1 on 2026-10-03 10:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0010_contract_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionDeclaration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("month", models.DateField()),
                ("filed_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_declarations",
                        to="wad.seller",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "constraints": [
                    models.UniqueConstraint(fields=("seller", "month"), name="unique_declaration_per_month")
                ],
            },
        ),
    ]
