# Generated by Django 6.1 on 2026-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wad", "0011_contributiondeclaration"),
    ]

    operations = [
        migrations.AddField(
            model_name="seller",
            name="pesel",
            field=models.CharField(blank=True, default="", max_length=11),
        ),
        migrations.AddField(
            model_name="seller",
            name="regon",
            field=models.CharField(blank=True, default="", max_length=14),
        ),
        migrations.AddField(
            model_name="seller",
            name="short_name",
            field=models.CharField(blank=True, default="", max_length=31),
        ),
    ]
