services:
  app:
    build:
      context: .
    pull_policy: build
    restart: unless-stopped
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_DB_PATH: /app/data/db.sqlite3
      DJANGO_STATIC_ROOT: /app/data/staticfiles
    volumes:
      - ./data:/app/data
    networks:
      - caddy_network
    labels:
      caddy: workanother.day
      caddy.encode: zstd gzip
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy_1: www.workanother.day
      caddy_1.redir: "https://workanother.day{uri} permanent"

networks:
  caddy_network:
    external: true
